name: Auto Close Issues

on:
  pull_request_target:
    types: [closed]

permissions:
  issues: write
  pull-requests: read

jobs:
  close-issues:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # PR이 머지된 경우에만 실행

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            const issues = body.match(/#(\d+)/g) || [];

            for (const issue of issues) {
              const num = issue.replace('#', '');
              try {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: parseInt(num),
                  state: 'closed'
                });
                console.log(`Successfully closed issue #${num}`);
              } catch (error) {
                console.error(`Failed to close issue #${num}:`, error);
              }
            }
